version: '3'

services:
  was:
    container_name: firefly-was
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '1323:1323'
    depends_on:
      - rdb
    links:
      - rdb:rdb
    volumes:
      - .:/go/src/app

  rdb:
    container_name: firefly-db
    image: mysql:8
    command: --character-set-server=utf8
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '43316:3306'
    environment:
      - MYSQL_DATABASE=firefly
      - MYSQL_USER=fireflylocal
      - MYSQL_PASSWORD=fireflylocalpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 3s
      timeout: 3s
      retries: 10

